Update schema.json
LaMednum/standard-mediation-num pull request #19
Opened 2024-04-02 12:12 UTC by celestinleroux

Nouvelle version du schéma de données (V2)

2024-04-02 12:15 UTC, marc-gavanier commented on schema.json
> +            "description": "Ce champ contient l'adresse email générique de contact du lieu. Si besoin, vous pouvez renseigner plusieurs courriels en les sépérant par un ";".",
```suggestion
            "description": "Ce champ contient l'adresse email générique de contact du lieu. Si besoin, vous pouvez renseigner plusieurs courriels en les sépérant par un ';'.",
```

2024-04-02 12:15 UTC, marc-gavanier commented on schema.json
> +            "description": "Ce champ permet d'informer si c'est un lieu de médiation itinérant comme un bus numérique, une cyber-caravane ou un camion connecté. Sélectionner une ou plusieurs valeurs
```suggestion
            "description": "Ce champ permet d'informer si c'est un lieu de médiation itinérant comme un bus numérique, une cyber-caravane ou un camion connecté. Sélectionner une ou plusieurs valeurs séparées par un point-virgule sans espace parmi la liste suivante : 'Itinérant;Fixe'",
```

2024-04-02 12:17 UTC, marc-gavanier commented on schema.json
> +                "pattern": "(?:(?:^|;)(Surdité|Handicaps moteurs|Handicaps mentaux|Illettrisme|Langues étrangères (anglais)|Langues étrangères (autres) sont tous des formes de déficience visuelle))+$
```suggestion
                "pattern": "(?:(?:^|;)(Surdité|Handicaps moteurs|Handicaps mentaux|Illettrisme|Langues étrangères \\(anglais\\)|Langues étrangères \\(autres\\)|Déficience visuelle))+$"
```

2024-04-02 12:18 UTC, marc-gavanier commented on schema.json
> +                "pattern": "(?:(?:^|;)(Aidants Connect|Bibliothèques numérique de référence|Certification PIX|Conseillers numériques|Emmaüs Connect|France Services|Grande école du numérique |La Croix
```suggestion
                "pattern": "(?:(?:^|;)(Aidants Connect|Bibliothèques numérique de référence|Certification PIX|Conseillers numériques|Emmaüs Connect|France Services|Grande école du numérique |La Croix Rouge|Point d'accès numérique CAF|Promeneurs du net |Relais numérique \\(Emmaüs Connect\\)))+$"
```

2024-04-02 12:19 UTC, marc-gavanier commented on schema.json
> +                "pattern": "(?:(?:^|;)(En autonomie|Accompagnement individuel|Dans un atelier collectif : j'apprends collectivement à utiliser le numérique|À distance (par téléphone ou en visioconfér
```suggestion
                "pattern": "(?:(?:^|;)(En autonomie|Accompagnement individuel|Dans un atelier collectif : j'apprends collectivement à utiliser le numérique|À distance \\(par téléphone ou en visioconférence\\)))+$"
```

2024-04-02 12:20 UTC, marc-gavanier commented on schema.json
> +            "example": "Dans un atelier collectif;À distance",
```suggestion
            "example": "Dans un atelier collectif (j'apprends collectivement à utiliser le numérique);À distance",
```

2024-04-02 12:21 UTC, marc-gavanier commented on schema.json
> +            "description": "Ce champ permet de préciser si le lieu a obtenu d’autres formations ou labels non proposés dans le champ "Formations et labels".",
```suggestion
            "description": "Ce champ permet de préciser si le lieu a obtenu d’autres formations ou labels non proposés dans le champ 'Formations et labels'.",
```

2024-04-02 12:21 UTC, marc-gavanier commented on schema.json
> +                "pattern": "(?:(?:^|;)(Formé à « Mon Espace Santé »|Formé à « DUPLEX » (illetrisme)|Arnia/MedNum BFC (Bourgogne-Franche-Comté)|Collectif ressources et acteurs réemploi (Normandie)|Fab
```suggestion
                "pattern": "(?:(?:^|;)(Formé à « Mon Espace Santé »|Formé à « DUPLEX » \\(illetrisme\\)|Arnia/MedNum BFC \\(Bourgogne-Franche-Comté\\)|Collectif ressources et acteurs réemploi \\(Normandie\\)|Fabriques de Territoire|Les Éclaireurs du numérique \\(Drôme\\)|Mes Papiers \\(Métropole de Lyon\\) |ORDI 3.0|SUD LABS \\(PACA\\)))+$"
```

2024-04-02 12:22 UTC, marc-gavanier commented on schema.json
> +            "description": "Ce champ indique si le lieu a obtenu un(e) ou plusieurs formations et labels. Cette liste est évolutive, si vous ne trouvez pas ce que vous cherchez vous pouvez vous référ
```suggestion
            "description": "Ce champ indique si le lieu a obtenu un(e) ou plusieurs formations et labels. Cette liste est évolutive, si vous ne trouvez pas ce que vous cherchez vous pouvez vous référer au champ 'Autres formations ou labels'. Sélectionner une ou plusieurs valeurs séparées par un point-virgule sans espace parmi la liste suivante : Formé à « Mon Espace Santé »;Formé à « DUPLEX » (illetrisme);Arnia/MedNum BFC (Bourgogne-Franche-Comté);Collectif ressources et acteurs réemploi (Normandie);Fabriques de Territoire;Les Éclaireurs du numérique (Drôme);Mes Papiers (Métropole de Lyon) ;ORDI 3.0;SUD LABS (PACA),
```

2024-04-02 15:19 UTC, Pierlou requested changes

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +    "contact": "contact@lamednum.coop, cartographie.sonum@anct.gouv.fr",
Pas sûr de cette pratique 🤔 Un seul email pourquoi pas (même si le champ `contact` n'est pas dans le standard TableSchema je crois), pour plusieurs je ne pense pas que les mettre comme ça soit une bonne idée. A voir pour migrer les adresses mails dans les contributeurs peut-être ? (cf [ici](https://github.com/etalab/schema-irve/blob/92bff45310792b0ffaff5094790392e15f83f0b9/statique/schema-statique.json#L36))

2024-04-02 15:19 UTC, Pierlou commented on schema.json
>              "constraints": {
Est-ce que vous souhaitez ajouter des contraintes sur le champ (afin qu'il ne soit pas possible d'y renseigner n'importe quelle valeur) ? Exemple [ici](https://github.com/etalab/schema-irve/blob/92bff45310792b0ffaff5094790392e15f83f0b9/statique/schema-statique.json#L114)

2024-04-02 15:19 UTC, Pierlou commented on schema.json
>              "name": "code_insee",
Pourquoi avoir à la fois le nom de la commune, le code postal et le code INSEE ? Ca me semble redondant et propice aux erreurs, et avec l'un des trois on peut retrouver les deux autres assez facilement. Possible de n'en garder qu'un ? (selon vos cas d'usage)

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +            "description": "Ce champ contient l'adresse email générique de contact du lieu. Si besoin, vous pouvez renseigner plusieurs courriels en les sépérant par un ';'.",
Le `;` est souvent utilisé comme séparateur dans les fichiers csv, peut-être choisir un caractère différent pour séparer les valeurs dans un champ (le `|` est une alternative souvent utilisée)

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +                "pattern": "(?:(?:^|;)(Itinérant|Fixe))+$"
La contrainte adéquate pour ce cas est `enum` (cf [ici](https://github.com/etalab/schema-irve/blob/92bff45310792b0ffaff5094790392e15f83f0b9/statique/schema-statique.json#L373))

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +                "pattern": "(?:(?:^|;)(Aide aux démarches administratives|Maîtrise des outils numériques du quotidien|Insertion professionnelle via le numérique|Utilisation sécurisée du numérique|Par
De même ici, privilégier `enum`

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +                "pattern": "(?:(?:^|;)(Jeunes|Étudiants|Familles et/ou enfants|Seniors|Femmes))+$"
Idem

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +                "pattern": "(?:(?:^|;)(Surdité|Handicaps moteurs|Handicaps mentaux|Illettrisme|Langues étrangères \\(anglais\\)|Langues étrangères \\(autres\\)|Déficience visuelle))+$"
Idem

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +                "pattern": "(?:(?:^|;)(Gratuit : Je peux accéder gratuitement au lieu et à ses services|Gratuit sous condition : La gratuité est conditionnée à des critères (adhésion, situation famil
Idem

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +                "pattern": "(?:(?:^|;)(Aidants Connect|Bibliothèques numérique de référence|Certification PIX|Conseillers numériques|Emmaüs Connect|France Services|Grande école du numérique |La Croix
Idem

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +                "pattern": "(?:(?:^|;)(Formé à « Mon Espace Santé »|Formé à « DUPLEX » \\(illetrisme\\)|Arnia/MedNum BFC \\(Bourgogne-Franche-Comté\\)|Collectif ressources et acteurs réemploi \\(Norm
Idem

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +                "pattern": "(?:(?:^|;)(Se présenter|Téléphoner|Contacter par mail|Prendre un RDV en ligne|Ce lieu n'accueille pas de public|Envoyer un mail avec une fiche de prescription))+$"
Idem

2024-04-02 15:19 UTC, Pierlou commented on schema.json
> +                "pattern": "(?:(?:^|;)(En autonomie|Accompagnement individuel|Dans un atelier collectif|À distance))+$"
Idem

2024-04-02 15:39 UTC, Pierlou commented on schema.json
>      "uri": "https://raw.githubusercontent.com/LaMednum/standard-mediation-num/v0.1.0/schema.json",
⚠️ il faut changer le numéro de version dans tous les champs qui le mentionnent (on a un outil qui arrive pour faire ça automatiquement, cf [ici](https://github.com/datagouv/tableschema-template/pull/8))

2024-04-02 15:43 UTC, marc-gavanier commented on schema.json
>              "name": "code_insee",
La quasi-totalité des données que nous recevons ne contiennent que le code postal et la commune. Nous appliquons effectivement une transformation pour retrouver les codes INSEE (nous effectivement de très nombreuses incohérences à cette occasion). Mais certains de nos réutilisateurs ont besoin du code INSEE.
Nous avons donc besoin de code postal+commune en entrée car nous n'avons pas le choix (le code INSEE serait idéal).
Et nous proposons le code INSEE en plus en sortie.
C'est pour cela que nous avons besoin de faire apparaître les trois dans le schéma

2024-04-02 16:35 UTC, celestinleroux commented on schema.json
> +    "contact": "contact@lamednum.coop, cartographie.sonum@anct.gouv.fr",
ça marche, dans ce cas on supprime le mail de la mednum :)

2024-04-02 16:35 UTC, celestinleroux commented on schema.json
>              "constraints": {
on le fait merci !

2024-04-08 14:15 UTC, Pierlou requested changes
Désolé pour les mauvaises recommandations de la review précédente, je n'avais pas en tête que des données étaient déjà publiées, et j'ai mal compris le besoin sur les champs avec choix multiples

2024-04-08 14:15 UTC, Pierlou commented on schema.json
> +            "description": "Ce champ contient une ou plusieurs URL vers le site internet du lieu et/ou les réseaux sociaux. Pour renseigner plusieurs URL, il est nécessaire de les séparer par une bar
Je reviens sur cette histoire de séparateur : j'ai vérifié (je n'avais pas pensé à le faire la dernière fois) et il y a déjà des fichiers publiés sur data.gouv sous l'égide du schéma (notamment [ici](https://www.data.gouv.fr/fr/datasets/lieux-de-mediation-numerique-sur-le-territoire-national-fournis-par-data-inclusion-1/)), donc ce n'est pas une bonne idée de changer les séparateurs, sinon il faudra repasser sur tous les fichiers déjà publiés. On peut rester sur le point virgule (qui garde malheureusement les inconvénients listés plus haut)

2024-04-08 14:15 UTC, Pierlou commented on schema.json
> +                "enum": [
La contrainte `enum` ne permet pas de renseigner plusieurs valeurs de la liste (j'avais mal lu votre besoin, désolé 😞). C'est bien une regex qu'il faut, celle d'origine était correcte, my bad (et on reste aussi sur le point virgule)

2024-04-08 14:15 UTC, Pierlou commented on schema.json
> +            "description": "Ce champ permet de décrire les types d'accompagnement proposés dans l'offre du lieu. Sélectionner une ou plusieurs valeurs séparées par un |  parmi la liste suivante :  Ai
De même ici, on reste sur point virgule + regex

2024-04-08 14:15 UTC, Pierlou commented on schema.json
> +            "description": "Par défaut, un lieu d'inclusion numérique est inclusif et peut accueillir tout public. Malgré tout, certains lieux sont habilités à recevoir exclusivement certains publics
De même ici, on reste sur point virgule + regex

2024-04-08 14:15 UTC, Pierlou commented on schema.json
> +            "description": "Ce champ permet d'informer si le lieu est en mesure d'accompagner et soutenir des publics ayant des besoins particuliers. Sélectionner une ou plusieurs valeurs séparées pa
De même ici, on reste sur point virgule + regex

2024-04-08 14:15 UTC, Pierlou commented on schema.json
> +            "description": "Ce champ indique les conditions financières d'accès au lieu. Sélectionner une ou plusieurs valeurs séparées par un | parmi la liste suivante : Gratuit : Je peux accéder gr
De même ici, on reste sur point virgule + regex

2024-04-08 14:15 UTC, Pierlou commented on schema.json
> +            "description": "Ce champ indique si le lieu appartient à un dispositif ou à un programme national. Sélectionner une ou plusieurs valeurs séparées par un | sans espace parmi la liste suiva
De même ici, on reste sur point virgule + regex

2024-04-08 14:15 UTC, Pierlou commented on schema.json
> +            "description": "Ce champ indique si le lieu a obtenu un(e) ou plusieurs formations et labels. Cette liste est évolutive, si vous ne trouvez pas ce que vous cherchez vous pouvez vous référ
De même ici, on reste sur point virgule + regex

2024-04-08 14:15 UTC, Pierlou commented on schema.json
> +            "description": "Ce champ fournit des informations sur les différentes étapes ou démarches à suivre pour se rendre au lieu d'inclusion numérique et bénéficier de ses services. Sélectionner
De même ici, on reste sur point virgule + regex

2024-04-08 14:15 UTC, Pierlou commented on schema.json
> +            "description": "Ce champ indique les types d'accompagnement proposés par le lieu. Sélectionner une ou plusieurs valeurs séparées par un | parmi la liste suivante : En autonomie;Accompagne
De même ici, on reste sur point virgule + regex

2024-04-08 14:15 UTC, Pierlou commented on schema.json
>      "created": "2022-07-04",
La version est `v0.2.0` (je peux installer l'utilitaire qu'on a créé pour les checks de versions si vous voulez)

2024-04-09 10:52 UTC, celestinleroux commented on schema.json
> +    "version": "0.2.0",
oui carrément merci

2024-04-09 10:52 UTC, celestinleroux commented on schema.json
> +            "description": "Ce champ contient une ou plusieurs URL vers le site internet du lieu et/ou les réseaux sociaux. Pour renseigner plusieurs URL, il est nécessaire de les séparer par une bar
ok je modif

2024-04-15 14:09 UTC, closed without merging